language: php

php:
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer update --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit

branches:
    except:
    - gh-pages
